### ISSUE TITLE
sourcelookup not evaluating a source

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#51]
For feature GB126 in sheet MM_kore1280 in grambank original sheet, there is a source listed as "Sohn (2015:324) Grammaticalization". I'm guessing this is because there is more than one work by Sohn from this year, and that it should be "Sohn_Grammaticalization (2015:324)". However, pygrambank sourcelookup doesn't seem to evaluate this source. When I run it on this sheet, I get:
```
Resolved sources:
155	g_Sohn_Korean	Sohn, Ho-min. 1994. Korean. (Descriptive Grammars Series.) London: Routledge. xvii+584pp.
120	g_Sohn_Korean_1999	Sohn, Ho-Min. 1999. The Korean language. Cambrige: Cambridge University Press. 462pp.
20	g_LeeRamsey_Korean	Iksop Lee and Ramsey, Robert S. 2000. The Korean Language. (SUNY Series in Korean Studies.) New York: State University of New York Press. xiii+374pp.

OK
```

Shouldn't it also check "Sohn (2015:324) Grammaticalization" and throw some kind of warning?

**Comment by xrotwang** [comment]
AFAICT Glottolog doesn't have anything by Sohn from 2015 in `hh.bib`. The problem here is that `sourcelookup` is happy as long as at least one reference can be matched per datapoint. So the unmatched `Sohn (2015:324) Grammaticalization` is simply read as some sort of comment.

**Comment by HedvigS** [comment]
Yes, I would want it to say that it tried matching Sohn 2015 to hh.bib or gb.bib and that it couldn't.

Right, okay. What can we do to change that? I know that sourcelookup already ignores things like "personal correspondence" etc, but in thise case we'd like it to try and resolve it (and fail).

**Comment by HedvigS** [comment]
Tha'd be great!

And maybe also some kind of warning for strings that include a space and something after the YEAR:PAGES. Like in this case the " grammaticalization".

**Comment by xrotwang** [comment]
fix pushed to master

**Comment by HedvigS** [comment]
Thank you

**Comment by HedvigS** [comment]
it used to be that the pygrambank cldf command ran sourcelookup on every sheet right, so that the output from there could be used for our "check warnings"-todo list. This is still the same with cldfbench right?

**Comment by HedvigS** [comment]
Okay, thanks. I'll try and re-install and run it so that I can update the to do list for automatic warnings.

**Comment by HedvigS** [comment]
cldfbench is complaining that the proto-languages, like ocea1241, doesn't have a macroaea. Is this something that mucks something up? Would you like me to submit a PR to glottolog/glottolog adding macroareas for family-level languoids?

**Comment by xrotwang** [comment]
Just  ignore this warning.

Hedvig Skirgård ***@***.***> schrieb am Mi., 12. Jan. 2022,
17:53:

**Comment by HedvigS** [comment]
Ok.

**Comment by HedvigS** [comment]
I can read in all the sheets line by line and then do a match to this output, but it'd be easier if it could report the sheet right away please.
